version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.3-stretch-node-browsers

install_dependencies: &install_dependencies
    run:
      name: Install Dependencies
      command: |
          sudo apt install awscli python-requests
          sudo npm install -g bower gulp karma-cli
          bower install
          npm install
          sudo pip install git+https://github.com/data-mermaid/mermaid-changelog.git

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - *install_dependencies
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Fetch local mermaid-config file
          command: aws s3 cp --region "us-east-1" s3://mermaid-config/mermaid-config.js ./src/mermaid-config.js
      - run:
          name: Build for tests
          command: |
              mkdir src/build
              gulp vendor
              gulp build
      - run:
          name: Run test
          command: karma start

  deploy_dev:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - *install_dependencies
      - run:
          name: Build
          command: |
              mkdir src/build
              echo 'var MERMAID_VERSION="'$CIRCLE_BRANCH'-'${CIRCLE_SHA1:0:7}'";' > src/build/app_version.js
              aws s3 cp --region "us-east-1" s3://mermaid-config/mermaid-config-dev.js ./src/mermaid-config.js
              gulp vendor
              gulp build
              gulp build-files-exist
              gulp generate-sw
              ./deploy.sh dev-collect.datamermaid.org
              curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "X-Auth-Email: $CF_EMAIL" -H "X-Auth-Key: $CF_KEY" -H "Content-Type: application/json" --data '{"purge_everything": true}'
      - run:
          name: Update version
          command: python ci_cd/update_version.py dev collect "${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"
      - run:
          name: Update changelog
          command: |
            chlog v0.12.0

  deploy_prod:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - *install_dependencies
      - run:
          name: Build
          command: |
              mkdir src/build
              echo 'var MERMAID_VERSION="'$CIRCLE_TAG'-'${CIRCLE_SHA1:0:7}'";' > src/build/app_version.js
              aws s3 cp --region "us-east-1" s3://mermaid-config/mermaid-config-prod.js ./src/mermaid-config.js
              gulp vendor
              gulp build
              gulp build-files-exist
              gulp generate-sw
              ./deploy.sh collect.datamermaid.org
              curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "X-Auth-Email: $CF_EMAIL" -H "X-Auth-Key: $CF_KEY" -H "Content-Type: application/json" --data '{"purge_everything": true}'
      - run:
          name: Update version
          command: python ci_cd/update_version.py prod collect "${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"
      - run:
          name: Update changelog
          command: |
            chlog ${CIRCLE_TAG}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: org-global
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
      - deploy_dev:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only: dev
      - deploy_prod:
          context: org-global
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
